/*
 * Album Store API
 *
 * CS6650 Fall 2023
 *
 * API version: 1.0.0
 * Contact: i.gorton@northeasern.edu
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	//"net/http"
	"github.com/gin-gonic/gin"
	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "northeastern.edu/yu.shangl/hw1/go"
)

func main() {
	log.Printf("Server started")

	//router := sw.NewRouter()
	router := gin.New()
	router.GET("/albums/:id", sw.GetAlbumByKey)
	router.POST("/albums", sw.NewAlbum)
	router.Run(":8080")
	//log.Fatal(http.ListenAndServe(":8080", router))
}
